### ISSUE TITLE
Cannot GET null

### ISSUE THREAD

**Issue by jmajnek** [yoichiro/oauth2-firebase#15]
Hi,

thanks for sharing your project. Unfortunately, I was not able to get it to work. I followed your instructions but I receive `Cannot GET null`.

Did I miss something?

Maybe this is related with this issue? https://github.com/firebase/firebase-functions/issues/27

BR

**Comment by dubocr** [comment]
Hi,

Try this url
`https://XXXXX.cloudfunctions.net/authorize/entry` as Authorize URL
intead of `https://XXXXX.cloudfunctions.net/authorize`

But now I'm locked in the authentication page with "Now loading..."

**Comment by dubocr** [comment]
Fixed by adding `XXXXX.cloudfunctions.net` in https://console.firebase.google.com/project/<YOUR_PROJECT_NAME>/authentication/providers authorized domains (and activating Google Sign In of course)

**Comment by jmajnek** [comment]
Thanks @dubocr . It worked.
